# Generated by Django 4.2.9 on 2024-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
