# Generated by Django 4.2.9 on 2024-02-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_review_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='details',
            new_name='detail',
        ),
    ]
