# Generated by Django 4.2.9 on 2024-02-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_alter_review_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='detail',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
